//! The adapter manifest describing how to drive this soar.
//!
//! A frontend that shells out to soar needs to know which arguments to pass
//! and how to read what comes back. Shipping that description inside the
//! binary means it always matches the binary that emitted it, which is the
//! whole point: a frontend linking soar as a library can fall out of step with
//! the soar the user actually runs, and this cannot.
//!
//! The shape is the one any package manager is described in, so a frontend has
//! a single code path and soar is not a special case.

/// The manifest format this describes itself in.
///
/// A reader should accept this and the version before it, and refuse anything
/// newer rather than guessing at fields it does not know.
const SCHEMA_VERSION: u32 = 1;

/// Describes the commands as this build actually accepts them.
///
/// `{selector}`, `{name}`, `{query}` and `{version}` are the only
/// substitutions. `selector` says how to build the first of those out of a
/// package's fields, so two projects publishing the same command name stay
/// told apart.
pub fn manifest() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# Generated by `soar plugin-manifest`. This describes the soar that
# emitted it, so it is worth regenerating rather than copying between machines.
schema_version = {SCHEMA_VERSION}
id = "soar"
name = "Soar"
version = "{version}"

# Most specific form first: a package published under a family is named by it,
# and one published without a family is named on its own.
selector = ["{{family}}/{{name}}", "{{name}}"]

[detect]
command = "soar"
version = ["--version"]
min_version = "{version}"

# Query commands answer with one JSON document; `items` is the array to read
# and `total` says how many matched before any limit was applied.
[ops.list]
args = ["--json", "list"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", installed = "installed" }}

[ops.list_installed]
args = ["--json", "info"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", family = "family", version = "version", repo = "repo", size = "disk_size", path = "installed_path", installed_at = "installed_date", pinned = "pinned", healthy = "healthy" }}

[ops.search]
args = ["--json", "search", "{{query}}"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", installed = "installed" }}

[ops.info]
args = ["--json", "query", "{{selector}}"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", checksum = "checksum", homepages = "homepages", licenses = "licenses", download_url = "download_url" }}

[ops.list_updates]
args = ["--json", "update", "--check"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", family = "family", repo = "repo", version = "current_version", current_version = "current_version", new_version = "new_version", size = "size" }}

[ops.list_repos]
args = ["--json", "repo", "list"]
output = {{ format = "json", select = "$.items[*]" }}
fields = {{ name = "name", url = "url", enabled = "enabled" }}

# Where soar keeps its files, so they can be read and written directly rather
# than through a command for every field.
[ops.paths]
args = ["--json", "env"]
output = {{ format = "json" }}
fields = {{ config = "config", packages_config = "packages_config", bin = "bin", db = "db", cache = "cache", packages = "packages", repositories = "repositories" }}

# What applying the declarative configuration would change, asked before it is
# applied rather than reported while it happens.
[ops.apply_check]
args = ["--json", "apply", "--dry-run"]
output = {{ format = "json" }}

# Operations answer with a stream instead: one JSON object per line, written as
# it happens, so progress can be shown while the work is still running.
[ops.install]
args = ["--json", "install", "--yes", "{{selector}}"]
output = {{ format = "ndjson" }}
progress = {{ event = "type", current = "current", total = "total", message = "pkg_name" }}

[ops.remove]
args = ["--json", "remove", "--yes", "{{selector}}"]
output = {{ format = "ndjson" }}
progress = {{ event = "type", message = "pkg_name" }}

[ops.update]
args = ["--json", "update"]
output = {{ format = "ndjson" }}
progress = {{ event = "type", current = "current", total = "total", message = "pkg_name" }}

[ops.sync]
args = ["--json", "sync"]
output = {{ format = "ndjson" }}
progress = {{ event = "type", message = "repo_name" }}

[ops.apply]
args = ["--json", "apply", "--yes"]
output = {{ format = "ndjson" }}
progress = {{ event = "type", current = "current", total = "total", message = "pkg_name" }}

# Repository commands report nothing on success, so there is no shape to read.
[ops.add_repo]
args = ["repo", "add", "{{name}}", "{{url}}"]
output = {{ format = "ndjson" }}

[ops.remove_repo]
args = ["repo", "remove", "{{name}}"]
output = {{ format = "ndjson" }}

[ops.set_repo_enabled]
args = ["repo", "update", "{{name}}", "--enabled", "{{enabled}}"]
output = {{ format = "ndjson" }}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_manifest_is_valid_toml() {
        let parsed: toml::Value = toml::from_str(&manifest()).expect("manifest must parse");
        assert_eq!(parsed["schema_version"].as_integer(), Some(1));
        assert_eq!(parsed["id"].as_str(), Some("soar"));
    }

    #[test]
    fn every_operation_names_a_real_subcommand() {
        use clap::CommandFactory;

        let parsed: toml::Value = toml::from_str(&manifest()).unwrap();
        let known: Vec<String> = crate::cli::Args::command()
            .get_subcommands()
            .map(|sub| sub.get_name().to_string())
            .collect();

        for (op, table) in parsed["ops"].as_table().expect("ops table") {
            let args = table["args"].as_array().expect("args array");
            // The first argument that is not a global flag is the subcommand.
            let subcommand = args
                .iter()
                .filter_map(|a| a.as_str())
                .find(|a| !a.starts_with('-'))
                .unwrap_or_else(|| panic!("{op} names no subcommand"));
            assert!(
                known.iter().any(|k| k == subcommand),
                "{op} runs `{subcommand}`, which this soar does not have"
            );
        }
    }
}
